Hide secrets
sushmita56/WeatherApp pull request #1
Opened 2021-07-26 08:30 UTC by sushmita56

I've hidden API key and Django secret key inside environment variables and then accessed that information from the code for the security purpose.  These changes allow me to conceal my secret keys in the windows environment variable and read them in code without actually writing them directly in the code.

2021-07-26 09:58 UTC, ritushishir requested changes

2021-07-26 09:58 UTC, ritushishir commented on weather/weatherapp/views.py
> +    # if request.method == 'POST':
can be removed this section?

2021-07-26 09:58 UTC, ritushishir commented on weather/weatherapp/views.py
> +                    error_msg = 'City doesnot exists.'
"City does not exist"?

2021-07-26 09:58 UTC, ritushishir commented on weather/weatherapp/views.py
> +    url = 'http://api.openweathermap.org/data/2.5/weather?q={}&units=imperial&appid=%s' %apiId
you are adding **apiID** at the end of the URL string, right? 
not sure about the syntax but it looks like something is missing. Does it work?

2021-07-26 09:59 UTC, ritushishir commented
Seems a lot of changes but it's great that the secrets are hidden now.  @sushmita56 👍

2021-07-27 02:08 UTC, ritushishir approved these changes

2021-07-27 03:11 UTC, sushmita56 commented on weather/weatherapp/views.py
> +    url = 'http://api.openweathermap.org/data/2.5/weather?q={}&units=imperial&appid=%s' %apiId
Yes! It does. I had run the code before committing the changes. It works well.

2021-07-27 03:11 UTC, sushmita56 commented on weather/weatherapp/views.py
> +    # if request.method == 'POST':
No, this part of the code is responsible for letting us know whether the "city" already exists  in the database or not. So I think it's good to be.

2021-07-27 16:40 UTC, ritushishir approved these changes

2021-08-09 02:58 UTC, merged